### ISSUE TITLE
🤷‍♀️

### ISSUE THREAD

**Issue by Tuvqlu** [ItsToxicGG/LDFx#18]
# Feature Requests

## Hub Titles

Commands:

- /htlocker, you can view all hub titles you own
- /hts, you can view all hub titles there are
- /createht, only for admins, to create a hub title
- /giveht, to give a player a hub title,  can be added to NPC’s 
- /ht help, help of course

idea: take inspiration from Hive

## Avatars

Commands:

- /avlocker, view all avatars you own
All same to hub titles just av and avatars instead

**Shows up on friends menu**

**Comment by ItsToxicGGAlt** [comment]
??

**Comment by ItsToxicGGAlt** [comment]
@Tuvqlu This Feature wont be expected soon! as of the development of v2.0, this feature would be delayed alot
